// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // ✅ Properly return web config
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl6o4ArmvGVA6O2NjENnItacjr71Vxezw',
    appId: '1:156136178849:android:12a87b072b0263756fdce0',
    messagingSenderId: '156136178849',
    projectId: 'otpverification-1aab0',
    storageBucket: 'otpverification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM421OsO75-gbl_axttXvaiN57C5y8HMI',
    appId: '1:125911462499:android:059345d37d5cf9b8d9fe56',
    messagingSenderId: '125911462499',
    projectId: 'dropikmed001-85982',
    storageBucket: 'gs://dropikmed001-85982.appspot.com',
    iosClientId:
        '356072704399-a1dufthi8066vj0fv6tnakvgp422e0eh.apps.googleusercontent.com',
    iosBundleId: 'com.netpair.dropikemapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDKEyfhT4DgXh_4tcFtiQrL29Ovhoxo0ug",
      authDomain: "otpverification-1aab0.firebaseapp.com",
      projectId: "otpverification-1aab0",
      storageBucket: "otpverification-1aab0.firebasestorage.app",
      messagingSenderId: "156136178849",
      appId: "1:156136178849:web:2a3447612b6794a76fdce0",
      measurementId: "G-F66M4Z5CM6");
}
